spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
---

spring:
  config:
    activate:
      on-profile: sandbox
server:
  port: 8081
---

spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8082